/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/layout/BottomBar/BottomBar.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    Main: typeof import('./src/layout/Main/Main.vue')['default']
    RightSideBar: typeof import('./src/layout/RightSideBar/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/layout/TopBar/TopBar.vue')['default']
  }
}
